---
title: "tumor_normal"
author: "ayman.abuelela"
date: "04/12/2020"
output: html_document
---
```{r}
# --- libraries ---#
## libraries ===================================================================
library(MASS)
library(gplots)
library(RColorBrewer)
library(caret)
library(heatmap.plus)
library(sparcl)
library(reshape2)
library(knitr)
library(pheatmap)
```

```{r}
# --- importing data ---#
dat = read.csv("~/Documents/projects/GTCancerClassifier/NormalvsTumor-0.2/TCGA_NormalvsTumor_RSEM_GTs.csv", header=T, row.names = 1)
dim(dat)

# select types with enough number normal:tumor
# select brca #224 - lusc 102 - kirc 144 - kipan 258 - luad 116
select <- c('brca', 'lusc', 'kirc', 'kipan', 'luad')
dat <- dat[dat$type %in% select, ]
```

```{r}
# -- preprocessing ---#
set.seed(61186)
pp = preProcess(dat, method=c("nzv", "center", "scale", "YeoJohnson"))
ppdat = predict(pp, dat)
ppdattype = split(ppdat, ppdat$type)


# --- visualisation ---#
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
pal = colorRampPalette(c("red", "black", "green"))(n = 128)

# --- dimensionality reduction ---#
for (i in 1:length(ppdattype)) {
    if (nrow(DF)>=100) {
    DF = ppdattype[[i]]
    matdat = as.matrix(DF[,-c(ncol(DF)-1,ncol(DF))])
    tissuecol = ifelse(DF$tissue=="normal", "red", "blue")
    ##PCA
    pca = prcomp(matdat)
    print(names(ppdattype)[i])
    print(kable(as.data.frame(head(t(summary(pca)$importance)))))
    }}

# --- hierarchial clustering ---#
for (i in 1:length(ppdattype)) {
    DF = ppdattype[[i]]
    if (nrow(DF)>=100) {
    matdat = as.matrix(DF[,-c(ncol(DF)-1, ncol(DF))])
    tissuecol = ifelse(DF$tissue=="normal", "red", "blue")
    dd = dist(matdat, method="euc")
    hh = hclust(dd, method="ward.D")
    ##hclust
    filename = file.path("~/Documents/projects/GTCancerClassifier/plots/", paste0(names(ppdattype)[i], "_dendogram.pdf"))
    #pdf(filename, width = 6, height = 3)
    ColorDendrogram(hc=hh, y=tissuecol,
                    branchlength = 34, main = names(ppdattype)[i] 
                    #labels = ss$mod_id
    )
    #dev.off()
}}
```
```{r}
# --- RDA model ---#
misclassrisk <- function(x) { 
    (sum(x) - sum(diag(x)))/sum(x) 
}
dattype = split(dat, dat$type)
rdafits = list()
rdafits2 = list()
for (i in 1:length(ppdattype)) {
    DF2 = dattype[[i]]
    set.seed(61186)
    intrain = createDataPartition(DF2$tissue, p=0.5, list=F)
    training = DF2[intrain,]
    testing = DF2[-intrain,]
    dim(testing)
    dim(training)
    set.seed(61186)
    pp  = preProcess(training, method=c("nzv", "scale", "center", "YeoJohnson"))
    pptraining = predict(pp, training)
    set.seed(61186)
    rdaGrid = data.frame(gamma = (1:4)/4, lambda = 0.75)
    ctrl = trainControl(method = "LOOCV",
                        summaryFunction = twoClassSummary,
                        classProbs = T,
                        savePredictions = T
                        #verboseIter = T
    )
    rdafits2[[i]] = train(tissue~., data = pptraining[, 1:61], method="rda", trControl=ctrl, tuneGrid=rdaGrid, metric="ROC")
    names(rdafits2)[i] = names(dattype)[i]
    pptesting = predict(pp, testing)
    pptesting$tissue <- as.factor(pptesting$tissue)
    rpreds = predict(rdafits2[[i]], pptesting)
    print(rdafits2[[i]]$finalModel)
    print(rdafits2[[i]])
    confmat = confusionMatrix(rpreds, pptesting$tissue)
    print(confmat)
    filename = file.path("~/Documents/projects/GTCancerClassifier/plots", paste0("rda_testing_confmat_",names(dattype)[i],".pdf"))
        pdf(filename, width = 4, height = 3)
        pheatmap(confmat$table,
                 display_numbers = T,
                 number_color = "black",
                 number_format = "%d",
                 color = colorRampPalette(brewer.pal(10, "Blues"))(13),
                 breaks = seq(0,65,5)
                 #border_color = NA
                 )
        dev.off()
    
    DF = ppdattype[[i]]
    matdat = as.matrix(DF[,-c(ncol(DF)-1, ncol(DF))])
    tissuecol = ifelse(DF$tissue=="normal", "red", "blue")
    ##RDA model
    
    if (nrow(DF)>=100) {
        print(names(ppdattype)[i])
        set.seed(61186)
        intrain = createDataPartition(DF$tissue, p=0.5, list=F)
        training = DF[intrain,-ncol(DF)]
        testing = DF[-intrain,-ncol(DF)]
        set.seed(61186)
        rdaGrid = data.frame(gamma = (1:4)/4, lambda = 0.75)
        ctrl = trainControl(method = "LOOCV",
                            summaryFunction = twoClassSummary,
                            classProbs = T,
                            savePredictions = T 
                            #verboseIter = T
                            )
        rdafits[[i]] = train(tissue~., data=training, method="rda", 
                             trControl=ctrl, tuneGrid= rdaGrid,
                             metric = "ROC"
                             )
        names(rdafits)[i] = names(ppdattype)[i]
        preds = predict(rdafits[[i]], testing)
        testing$tissue <- as.factor(testing$tissue)
        confmat = confusionMatrix(preds, testing$tissue)
        print(confmat$byClass)
        print(confmat)
        filename = file.path("../../plots", paste0("rda_testing_confmat_",names(ppdattype)[i],".pdf"))
        pdf(filename, width = 4, height = 3)
        pheatmap(confmat$table,
                 display_numbers = T,
                 number_color = "black",
                 number_format = "%d",
                 color = colorRampPalette(brewer.pal(10, "Blues"))(13),
                 breaks = seq(0,65,5)
                 #border_color = NA
                 )
        dev.off()
        #print(confusionMatrix(rdafits[[i]]))
        print(rdafits[[i]]$finalModel)
        print(rdafits[[i]])
        #print(plot(varImp(rdafits[[i]]), top=55))

    }
}
```

```{r}
# --- LDA ---#
for (i in 1:length(ppdattype)) {
    DF = ppdattype[[i]]
    matdat = as.matrix(DF[,-c(56,57)])
    tissuecol = ifelse(DF$tissue=="normal", "red", "blue")
    if (nrow(DF)>=100) {
        ## LDA
        set.seed(61186)
        ldafit = lda(tissue~., DF[,-ncol(DF)])
        preds.lf = predict(ldafit, DF)
        plotdat = data.frame(
            tissue = DF$tissue,
            ld = preds.lf$x[,1]
        )
        p2 = ggplot(plotdat, aes(x=tissue, y=ld, fill=tissue))+
            geom_boxplot()+
            theme_bw()+
            scale_fill_manual(values = c("red", "blue"))+
            theme(legend.position = "none")+
            ylab("LD")
        filename = file.path("~/Documents/projects/GTCancerClassifier/plots/", paste0("lda_", names(ppdattype)[i], ".pdf"))   
        ggsave(plot=p2, filename=filename, width=2, height=4, useDingbat=F)
        print(p2)
        
        # p2 = ggplot(as.data.frame(preds.lf$x), aes(preds.lf$x[,1], fill=DF$tissue))+
        #     geom_histogram(aes(y=1*..density..), alpha=0.3, color="black", 
        #                    position="identity", bins=40)+
        #     geom_density(alpha=0.1, linetype=2)+
        #     theme_bw()+
        #     scale_fill_manual(values=c("darkred", "darkblue"))
        # print(p2)
    }
}
```

```{r}
# TODO -- if needed
# --- ? ---#
for (i in 1:length(ppdattype)) {
    print(length(rdafits))
    DF = ppdattype[[i]]
    matdat = as.matrix(DF[,-c(ncol(DF)-1, ncol(DF))])
    pca = prcomp(matdat)
    tissuecol = ifelse(DF$tissue=="normal", "red", "blue")
    if (nrow(DF)>=100) {
        ## Feature importance
        set.seed(61186)
        ldafit = lda(tissue~., DF[,-ncol(DF)])
        preds.lf = predict(ldafit, DF)
        
        glevels = row.names(pca$rotation)[order(pca$rotation[,1])]
        glevels = factor(glevels, levels = glevels)
        
        ss = data.frame(importance = varImp(rdafits[[i]])$importance[,1],
                        gene = rownames(varImp(rdafits[[i]])$importance)                
        )
        ss = ss[order(ss$importance, decreasing = F),]
        ss$gene = factor(ss$gene, levels = ss$gene)
        mm = melt(ldafit$means)
        mm2 = data.frame(
            Var1 = rep("Importance", nrow(ss)),
            Var2 = ss$gene,
            value = ss$importance
        )
        mm2$Var2 = factor(mm2$Var2, levels = ss$gene)
        #mm3 = rbind(mm, mm2)
        mDF = melt(DF[,-57], id.vars = c("tissue"))
        mDF$variable = factor(mDF$variable, levels = glevels)
        sdDF = dcast(mDF, variable~tissue, fun.aggregate = sd)
        msdDF = melt(sdDF)
        msdDF = data.frame(
            Var1 = msdDF[,2],
            Var2 = factor(msdDF[,1], levels = ss$gene),
            value = msdDF$value
        )
        msdDF = msdDF[order(msdDF$Var2),]
        mm3 = merge(mm, msdDF, by = c("Var1", "Var2"))
        mm3$Var2 = factor(mm3$Var2, levels = ss$gene)
        names(mm3)[3:4] = c("value", "sd")
        
        p3 = ggplot(mm3, aes(Var2, value))+
            #geom_bar(stat="identity")+
            geom_point(aes(x=mm3$Var2, y=mm3$value, color=mm3$Var1, group=mm3$Var1))+
            geom_errorbar(width=0.2, aes(ymin=mm3$value-mm3$sd, ymax=mm3$value+mm3$sd, group=mm3$Var1, color=mm3$Var1), size=0.2)+
            #geom_jitter(aes(x=mDF$variable, y=mDF$value, color=mDF$tissue), alpha=0.07)+
            geom_line(aes(mm3$Var2, mm3$value, color=mm3$Var1, group=mm3$Var1))+
            scale_color_manual(values = c("red", "blue", "gray"))+
            geom_hline(yintercept = 0, linetype=2, color="black")+
            theme_bw()+
            coord_flip()
        print(p3)
        filename=file.path("./Screenshots/", paste0("exp_", names(ppdattype)[i], ".pdf"))
        ggsave(plot=p3, filename = filename, width=4, height=7, useDingbat=F)
        p4 = ggplot(mm2, aes(Var2, value))+
            geom_bar(fill="gray", stat = "identity", alpha=0.5)+
            theme_bw()+
            coord_flip()
        print(p4)
    }
}

# --- visualisation ---#
for (i in 1:length(ppdattype)) {
    message(i)
    DF = ppdattype[[i]]
    matdat = as.matrix(DF[,-c(ncol(DF)-1, ncol(DF))])
    tissuecol = ifelse(DF$tissue=="normal", "red", "blue")
    if (nrow(DF)>=100) {
        filename = file.path("~/Documents/projects/GTCancerClassifier/plots", paste0("heatmap_", names(ppdattype)[i], ".pdf"))
        pdf(filename, width = 7, height = 4)
        ##heatmapreds = predict(rdaall, testing)
        matdat2 = matdat[,order(varImp(rdafits[[i]])$importance[,1])]
        heatmap(matdat2, trace="none", hclustfun = function (x) {
            hclust(dist(matdat, method = "euc"), method = "ward.D")
        }, #distfun = dd,
        col=pal, Colv = NA,
        RowSideColors = tissuecol)
        dev.off()
    }
}
```

```{r}
# --- ? ---#
ppdat$tistyp = paste0(ppdat$tissue, ppdat$type)
typesubset = c("brca", "kipan", "kirc", "lihc", "luad", "lusc")
ssppdat = ppdat[ppdat$type %in% typesubset,]
#pca = prcomp(ssppdat)
ldaall = lda(tistyp~., ssppdat[,-c(ncol(DF)-1, ncol(DF))])
pldaall = predict(ldaall, ssppdat)
# ggplot(as.data.frame(pldaall$x), aes(LD1, LD2, shape=ssppdat$tissue, color=ssppdat$type))+
#     geom_point()
# id = ssppdat$tistyp
# ldadat = cbind(id, pldaall$x)
# write.csv(ldadat, "/media/ayman/D3/CancerClassifier/NormalvsTumor/ldadatall.csv", row.names = F, quote = F)
##########
```

```{r}
# --- rdall --#
dat$tistyp = paste0(dat$tissue, dat$type)
ssdat = dat[dat$type %in% typesubset,]
ssdat$tistyp2 = gsub("normalkipan|normalkirc", "normalkidney", ssdat$tistyp)
ssdat$tistyp2 = gsub("tumorkipan|tumorkirc", "tumorkidney", ssdat$tistyp2)
ssdat$tistyp2 = gsub("normalluad|normallusc", "normallung", ssdat$tistyp2)
ssdat$tistyp2 = gsub("tumorluad|tumorlusc", "tumorlung", ssdat$tistyp2)


set.seed(61186)
ssdat$tistyp2 <- as.factor (ssdat$tistyp2)
intrain <- createDataPartition(ssdat$tistyp2, p = 0.7, list = F, times=1)
training = ssdat[intrain,]
testing = ssdat[-intrain,]

set.seed(61186)
pp = preProcess(training, method=c("nzv", "scale", "center", "YeoJohnson"))
pptraining = predict(pp, training)
set.seed(61186)
ctrl = trainControl(method = "repeatedcv",
                    number = 10,
                    repeats = 10,
                    #summaryFunction = multiClassSummary,
                    classProbs = T,
                    savePredictions = T,
                    verboseIter = T
                    )
#rdaall2 = train(factor(tistyp2)~., data = pptraining[,-c(ncol(pptraining)-2:ncol(pptraining))], method="rda", tuneGrid=rdaGrid, trControl=ctrl, metric="ROC")

hold <- c('tissue', 'type', 'tistyp')
TrainData <- pptraining[, !colnames(pptraining) %in% hold]
TrainClasses <- as.factor(pptraining$tistyp2)
rdaall2 = train(TrainData,TrainClasses,  method="rda", tuneGrid=rdaGrid, trControl=ctrl, metric="ROC")

pptesting = predict(pp, testing)
preds2 = predict(rdaall2, pptesting)
confmat <- confusionMatrix(preds2, testing$tistyp2)

set.seed(61186)
ssppdat$tistyp2 = gsub("normalkipan|normalkirc", "normalkidney", ssppdat$tistyp)
ssppdat$tistyp2 = gsub("tumorkipan|tumorkirc", "tumorkidney", ssppdat$tistyp2)
ssppdat$tistyp2 = gsub("normalluad|normallusc", "normallung", ssppdat$tistyp2)
ssppdat$tistyp2 = gsub("tumorluad|tumorlusc", "tumorlung", ssppdat$tistyp2)
# intrain = createDataPartition(ssppdat$tistyp2, p=0.7, list = F)
# training = ssppdat[intrain,]
# testing = ssppdat[-intrain,]
# set.seed(61186)
# ctrl = trainControl(method = "repeatedcv",
#                     number = 10,
#                     repeats = 10,
#                     #summaryFunction = multiClassSummary,
#                     classProbs = T,
#                     savePredictions = T#,
#                     #verboseIter = T
#                     )
# rdaall = train(factor(tistyp2)~., data = training[,-c(56:58)], method="rda", tuneGrid=rdaGrid, trControl=ctrl, metric="ROC")
# preds = predict(rdaall, testing)
# confmat = confusionMatrix(preds, testing$tistyp2)
print(confmat$byClass)
print(confmat)
filename = file.path("./Screenshots/", "rdall_testing_confmat.pdf")
pdf(filename, width = 5, height = 4)
pheatmap(confmat$table,
         display_numbers = T,
         number_color = "black",
         number_format = "%d",
         color = colorRampPalette(brewer.pal(10, "Blues"))(10),
         cluster_rows = F, cluster_cols = F
         #border_color = NA
        )
dev.off()
print(confusionMatrix(rdaall2))
filename = file.path("./Screenshots/", "rdall_CV_confmat.pdf")
pdf(filename, width = 5, height = 4)
pheatmap(confusionMatrix(rdaall2)$table,
         display_numbers = T,
         number_color = "black",
         number_format = "%.0f",
         color = colorRampPalette(brewer.pal(10, "Blues"))(10),
         cluster_rows = F, cluster_cols = F
         #border_color = NA
        )
dev.off()
print(rdaall2$finalModel)
print(rdaall2)
```

